// Generated by Flexc++ V2.11.00 on Tue, 21 Mar 2023 12:37:07 +0100

#ifndef Scanner_H_INCLUDED_
#define Scanner_H_INCLUDED_

// $insert baseclass_h
#include "Scannerbase.h"


// $insert classHead
class Scanner: public ScannerBase
{
                        // Path of #include file
    std::string d_includePath;
                        // The current file being scanned
    std::string d_currentFile;
                        // Filenames of paths we are currently scanning
    std::vector<std::string> d_currentlyScanning;
    public:
        explicit Scanner(std::istream &in = std::cin, std::ostream &out = std::cout, bool keepCwd = true);

        Scanner(std::string const &infile, std::string const &outfile, bool keepCwd = true);
        
        // $insert lexFunctionDecl
        int lex();

    private:
        int lex_();
        int executeAction_(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must 
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum_ type);    
                            // re-implement this function for code that must 
                            // be exec'ed after the rules's actions.
};

// $insert scannerConstructors
inline Scanner::Scanner(std::istream &in, std::ostream &out, bool keepCwd)
:
    ScannerBase(in, out, keepCwd)
{}

inline Scanner::Scanner(std::string const &infile, std::string const &outfile, bool keepCwd)
:
    ScannerBase(infile, outfile, keepCwd)
{}

// $insert inlineLexFunction
inline int Scanner::lex()
{
    return lex_();
}

inline void Scanner::preCode() 
{
    // optionally replace by your own code
}

// TODO: Own file
inline void Scanner::postCode([[maybe_unused]] PostEnum_ type) 
{
  if (type == PostEnum_::POP)
  {
    d_currentlyScanning.pop_back();
    d_currentFile = d_currentlyScanning.back();
  }
}

inline void Scanner::print() 
{
    print_();
}


#endif // Scanner_H_INCLUDED_

